### ISSUE TITLE
Add advisory year dropdown to 'add image' page. 

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#125]
The function to select the advisory year with photos and snowpits is gone. We want it back. default should be 17-18

**Comment by jimurl** [comment]
Related to #126 and #127 
Doug and I decided to make the 'advisory year' automatically set, and then hide it from view. #85
I screwed it up and was defaulting the recent images to NEXT year, like 18-19 for this year ( it would continue to be off every year). 
I got that fixed, and reset the advisory years for the existing images.
