### ISSUE TITLE
Graphics on advisories that aren't '/advisory'

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#184]
On advisories that have the link ending with the date e.g., 17/10/24 the blue bar on the 'mountain weather' and 'snowpack discussion' headings is missing and the light gray bar below 'submit observations' button is missing. I think that is it, but there may be other I haven't noticed yet. 

This happens on the current and archived advisories that end /advisory/17/10/23. The graphics look good on /advisory.

**Comment by jimurl** [comment]
Good catch
