### ISSUE TITLE
time and date for featured weather stations on regional pages

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#197]
On Cooke regional page, first digit of Lulu time is cutoff. says 0:00 when it is 10:00.

Dates for some stations on regional pages are 11/1 while other stations are 11/01. Can we make these consistent, one or the other. I think 11/01 reads best, but maybe 11/1 saves some space.

**Comment by jimurl** [comment]
OK, fixed Lulu time. 
ON the dates - those come straight from whatever the data is in the original feed: SNOTEL sites don't have the leading zero, you all's weather stations output with the leading zero. I think it's possible to add a zero if one is not there.

**Comment by amarienthal** [comment]
Sounds good. I think it is fine to ignore the presence/absence of the leading zero for now.

**Comment by jimurl** [comment]
Done, but can't check lionhead fully yet, but it will almost certainly work.
