### ISSUE TITLE
Change subscribe button to MailChimp account

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#201]
we are going to use mailchimp for e-mail now. Change the subscribe on web/email to enroll people there.

**Comment by jimurl** [comment]
OK, there is some configuration on the MailChimp site. Do we want to continue to ask people for city / state?

**Comment by jimurl** [comment]
Link in menu changed to go to : http://eepurl.com/c9TK75
Link in footer produces new popup box.
