### ISSUE TITLE
Education pages

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#202]
Can we put a photo on the https://www.mtavalanche.com/education ?

Can we import our old descriptions from https://www.mtavalanche.com/education/classes/workshops ? Or use the old descriptions and make the new page look better?

In menu for 'Education' move 'Avalanche Classes' above 'online tutorials'

**Comment by jimurl** [comment]
its got a photo now.
Those descriptions are the same as the old site. Yes, they need improving.
Doug and I talked a bit about importing data from the Google Calendar and then re-displaying it in our own way.
Moved around menu items
