### ISSUE TITLE
caching?

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#234]
Data for Ridge at Bridger was just one hour behind while I was logged in, then didn't show at all when I logged out. Other Bridger stations are up to date and show.

**Comment by amarienthal** [comment]
It just popped up after some refreshes. Maybe just an issue with my browser and logging in/out.

**Comment by amarienthal** [comment]
Did you notice station data that comes from the ftp.mtavalanche site froze at 0100 this morning, then updated at 0700. Is that a caching thing?

**Comment by jimurl** [comment]
Using #177 to track this
