### ISSUE TITLE
Cache render for avalanche events/incidents

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#324]

**Comment by jimurl** [comment]
Map needs to be refreshed.

**Comment by jimurl** [comment]
This should be accomplished by setting the incidents view -> Advanced -> caching -> time 5 minutes

**Comment by jimurl** [comment]
this might be handled by setting the view cache time and putting the map in the header.

**Comment by jimurl** [comment]
Please do this test: next time you add a pit to SnowPilot, look at the map above the snowpit profiles page for your new pit ( perhaps even before you add the image to the gnfac website - that shouldn't matter).

It might not show up for up to 5 minutes. But it should eventually appear on the map. 

This is to test a caching issue (should be fixed); so if you if you click: funny drupal guy-> Flush All Caches -> Flush render cache , then the map will certainly be updated. But we want it to happen every 5 minutes, automatically.
