### ISSUE TITLE
SWE. video icon.

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#332]
Change link to SWE on weather map page to: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/or/snow/?cid=nrcs142p2_046155

On incidents and activity, the video icon shows up with the ones that have images, but should only show if there is a video. I think the Saddle Peak slide is the only one with a video at the moment.

**Comment by jimurl** [comment]
OK, I had to rewrite the 'Advisory embed All ' function; it was a messy bit of code that I left behind from last year, it's used in a lot of places like the GNFAC News on the homepage; archived advisories; media articles page theoretically lists images and videos that are attached.
