### ISSUE TITLE
High mountain adventures cam on Centennials works on its parent site, but on the regional page

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#378]
Can we get that back on the regional page? Thanks

**Comment by jimurl** [comment]
So, looking into this, I simplified much of the code and replaced it with a single image, which gets update fed from their website. But it still only loads slowly sometimes. Status bar indicates waiting on Youtube, but that doesn't seem relevant. The webcam image does eventually load after waiting on youtube is done. Perhaps there is some particular youtube video that the thumbnail images is perennially slow.

With improvements, works fine on d8 site.
