### ISSUE TITLE
A few website 'glitches' IG feed/dropdown menus

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#393]
1) Instagram feed is not currently on Home Page. Please re-add it below the map and calendar.
2) drop down menus drop behind the regional page links on any page that has those links across the top. weather dropdown menu also ends up behind the map on the snowpilot page, and on the weather stations links page.

**Comment by jimurl** [comment]
The menu dropdowns should be fixed. Please check as there are some significant differences between FF / Safari / Chrome on a Mac. Please check windows browsers.
Creating a new incident for the instagram feed problem, which is larger.
