### ISSUE TITLE
On snowpilot map danger is shown for Centennials

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#394]
Danger rating for Centennials is colored on the map on the snowpilot page, but not any other maps. It should only be colored when there is a warning there.

**Comment by jimurl** [comment]
Good catch.
This occurred in three places: the map on the snowpits page, the weather map page, and the placenames map. I updated all three to show gray 'None' , except when the hazard is high or extreme, or when there is an avalanche hazard. 

Next time any of these conditions are met ( high avy hazard in the centennials, darn that would have been yesterday ), then please check these maps for proper hazard rating color and outline.
